name: GitHub Actions Demo
run-name: ${{ github.actor }} is learning github actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Thank you
        uses: stkim7/actions-thank-you-new@master
        
      - run: |
          set +x
          echo "event: ${{github.event_name}}"
     
      
 
